[package]
name = "aarch64-linux-gnu_template_project"
version = "0.1.0"
authors = ["Kawamura Hideo <kawa90@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
